# Generated by Django 4.0.5 on 2023-08-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='background',
            field=models.ImageField(default='https://picsum.photos/200/100', upload_to=''),
        ),
    ]
