# Generated by Django 4.0.5 on 2023-08-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_workspace_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='background',
            field=models.ImageField(default='defaultWorkspace.jpg', upload_to=''),
        ),
    ]
