# Generated by Django 4.0.5 on 2023-08-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_workspace_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='background',
        ),
        migrations.AddField(
            model_name='board',
            name='background',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
