# Generated by Django 4.0.5 on 2023-08-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_workspace_background_board_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
